fyp/core/urls.py
from django.urls import path
from core import views


app_name = 'core'

urlpatterns = [
	path('', views.index, name='index'),
	path('about/', views.AboutView.as_view(), name='about'),
	path('register/', views.register, name='register'),
	path('redirected/', views.redirected, name='redirected'),
	path('redirected/notifications/<int:notification_id>', views.view_message_from_notification, name='noti_redirect'),
	path('professorregister/', views.professor_register, name='proRegister'),
	path('candidateregister/', views.candidate_register, name='canRegister'),
	path('logout/', views.user_logout, name='logout'),
	path('dashboard/', views.show_dashboard, name='dashboard'),
	path('dashboard/uploadfile/', views.upload_file, name='uploadfile'),
	path('dashboard/file/<int:file_id>', views.edit_file, name='edit_file'),
	path('dashboard/file/<int:file_id>/sendMessage', views.dispose_message_form, name='send_message'),
	path('dashboard/file/<int:file_id>/delete', views.delete_file, name='delete_file'),
	path('dashboard/messages', views.show_message, name='show_message'),
	path('dashboard/messages/compose', views.send_message, name='send_message'),
	path('dashboard/messages/outbox', views.outbox, name='outbox'),
	path('dashboard/messages/trash', views.trash, name='trash_box'),
	path('dashboard/connection', views.connection, name='connection'),
	path('dashboard/connection/createGroup', views.create_group, name='create_group'),
	path('view/<int:message_id>', views.view_message, name='view_message'),
	path('view/redirected/<int:message_id>/', views.save_file, name='save_file_in_message'),
	path('dashboard/notifications/unread', views.notifications_unread, name='view_notifications'),
	path('dashboard/notifications/all',views.notifications_all, name='all_notifications'),
	path('dashboard/notifications/mark-all-as-read', views.mark_all_as_read, name='mark_all_as_read'),
	path('dashboard/notifications/delete-all', views.delete_all_read_notifications, name='delete_all_read_notifications'),
	path('dashboard/connection/add', views.AddNewRelationship.as_view(), name='add_new_relationship'),
]

fyp/fyp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('core/', include('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fyp/core/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import TemplateView

from core.forms import UserForm, UserProfessorForm, UserCandidateForm, IdentityForm, FileForm, EditFileForm
from core.forms import sendMessageForm, ComposeForm, GroupForm, AddGroupForm, RelationshipForm
from core.models import File, Message, Group, Notification
from django.core.files import File as File_Django
import os
from django.utils import timezone
from core.helper_functions import validate_add_user


User = get_user_model()



def index(request):
    """
    A index page for the website.
    Redirect to the dashboard if the user logged in.
    Otherwise, let the user login use the email and password.
    """
    if request.user.is_authenticated:
        return redirect('core:dashboard')
    else:
        if request.method == 'POST':
            email = request.POST.get('email')
            password = request.POST.get('password')

            user = authenticate(email=email, password=password, key="UserLogIn")

            if user:
                # Only log the user in if he is not one of the staffs.
                if user.is_candidate or user.is_professor:
                    login(request, user)
                    return redirect('core:dashboard')
                else:
                    return HttpResponse("You are a staff of this website, try using another site for logging in.")
            else:
                # Bad login details are provided.  The user cannot login.
                print("Invalid login details: {0}, {1}".format(email, password))
                return HttpResponse("Invalid login details supplied.")
        else:
            return render(request, 'core/index.html')


class AboutView(TemplateView):
    """
    About page
    """
    template_name = 'core/profile_card.html'


def redirected(request):
    """
    A middle function to dispose the sign up identification.
    """
    if request.method == 'POST':
        identity = request.POST.get('identity')

        if identity == "professor":
            return redirect(reverse('core:proRegister'))
        else:
            return redirect(reverse('core:canRegister'))
    else:
        return HttpResponse("Something goes wrong.")


def register(request):
    """
    The first step of the registration, which require the user to select their identification.
    """
    identity_form = IdentityForm()
    context_dictionary = {'identity_form': identity_form}
    return render(request, 'core/registration_first_step.html', context_dictionary)


def professor_register(request):
    """
    The function to dispose the sign up detail for a professor.
    """
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfessorForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.is_professor = True
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True

            new_user = authenticate(email=user_form.cleaned_data['email'], password=user_form.cleaned_data['password'],
                                    key="UserLogIn")

            login(request, new_user)

            return redirect(reverse('core:dashboard'))

        else:
            print(user_form.errors, profile_form.errors)

    else:

        user_form = UserForm()
        profile_form = UserProfessorForm()

    return render(request,
                  'core/professor_registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def candidate_register(request):
    """
    A function to dispose the sign up detail for a candidate.
    """
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserCandidateForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.is_candidate = True
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            """
            Reference for using this:
            https://docs.djangoproject.com/en/dev/topics/forms/modelforms/#the-save-method
            """
            profile_form.save_m2m()

            registered = True

            new_user = authenticate(email=user_form.cleaned_data['email'], password=user_form.cleaned_data['password'],
                                    key="UserLogIn")

            login(request, new_user)

            return redirect(reverse('core:dashboard'))

        else:
            print(user_form.errors, profile_form.errors)

    else:

        user_form = UserForm()
        profile_form = UserCandidateForm()

    return render(request,
                  'core/candidate_registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('core:index'))


@login_required
def show_dashboard(request):
    """
    Show the dashboard of the user.
    """
    if request.method == 'GET':
        context = {}
        # The user should have logged in based on the decorator @login_required
        user = request.user
        context['user'] = user
        context['files'] = user.userfiles.all()
        if user.is_professor:
            profile = user.professor
            context['profile'] = profile
            # Later change this so that a professor and a candidate will have a different view based on their identity.
            return render(request, 'core/dashboard.html', context)
        elif user.is_candidate:
            profile = user.candidate
            context['profile'] = profile
            return render(request, 'core/dashboard.html', context)
        else:
            return HttpResponse("You are a staff of this website, try using this site for logging in.")


@login_required
def upload_file(request):
    """
    A view to let the user upload the file.
    The uploaded file will be saved as a File object.
    user: request.user
    description: Uploaded in the form.
    file: Uploaded in the form.
    name: Will be auto recorded as the file name.
    This can lead to FileExistError.
    created: Auto created.
    modified: When the description or the name of the file is changed.
    """
    if request.method == "POST":
        form = FileForm(request.POST, request.FILES)

        # An instance of class UploadedFile
        uploaded_file = request.FILES['file']
        if form.is_valid():
            # file is the File object while the uploaded_file is the file object.
            file = form.save(commit=False)
            file.user = request.user
            # upload_file.name is only the name of the file, rather than the path.
            # "test.txt for example."
            file.name = uploaded_file.name
            file.save()
            return redirect('core:dashboard')
        else:
            print(form.errors)
    else:
        form = FileForm()
        return render(request, 'core/upload_file.html', {
            'form': form,
        })


# Possible reference: https://stackoverflow.com/questions/604266/django-set-default-form-values
# for the default values in the django form.
# Possible reference: https://stackoverflow.com/questions/39919012/django-python-show-pdf-in-a-template
# to have a preview in the page.
# For pop up forms:
# https://stackoverflow.com/questions/52501470/i-want-to-create-django-popup-form-in-my-project/52501740
# Use the modals:
# https://getbootstrap.com/docs/4.2/components/modal/


@login_required
def edit_file(request, file_id):
    context = {}
    user = request.user
    file = get_object_or_404(File, id=file_id)
    if file.user != user:
        raise Http404
    context['file'] = file

    if request.method == "POST":
        form = EditFileForm(request.POST, instance=file)
        if form.is_valid():
            form.save()
        else:
            print(form.errors)
    else:
        form = EditFileForm(instance=file)
    context['form'] = form
    share_form = sendMessageForm(initial={'file': file.file})
    context['share_form'] = share_form
    return render(request, 'core/edit-file.html', context)


def delete_file(request, file_id):
    file = File.objects.get(id=file_id)
    file.delete()
    return redirect('core:dashboard')


def filename(s):
    """
    Return the filename from a path.
    Reference:
    https://stackoverflow.com/questions/2683621/django-filefield-how-to-return-filename-only-in-template
    """
    return os.path.basename(s)


@login_required
def dispose_message_form(request, file_id):
    """
    Dispose the modal share button.
    Reference:
    https://stackoverflow.com/questions/1347791/unicode-error-unicodeescape-codec-cant-decode-bytes-cannot-open-text-file
    https://docs.djangoproject.com/en/3.0/ref/unicode/
    The above website gives an idea that we should use the UTF-8 as the default encoding for

fyp/templates/core/ProfessorRegister.html
{% extends 'core/base.html' %}
{% load staticfiles %}


{% block title_block %}
    Professor Register
{% endblock %}

{% block body_block %}
    <h1>Register page for the professor</h1>

	{% if registered %}
		<strong>Thank you for registering as an professor!</strong>

	{% else %}
		<strong>Register here!</strong>
		<form id="user_form" method="post" action="{% url 'core:proRegister' %}"
			enctype="multipart/form-data">

			{% csrf_token %}


			{{ user_form.as_p }}

			{{ profile_form.as_p }}

			<input type="submit" name="submit" value="Register" />

		</form>
	{% endif %}

{% endblock %}

fyp/templates/core/about.html
{% extends 'core/base.html' %}
{% load staticfiles %}

{% block title_block %}
    about
{% endblock %}

{% block body_block %}
    <h1>
    Write something about the about page later.
    </h1>
{% endblock %}

fyp/templates/core/all_notifications.html
{% extends 'core/base.html' %}


{% block title_block %}
    All Notifications
{% endblock %}


{% block Notification2_tag %}
    active
{% endblock %}

{% block body_block %}
        <!--A container for showing the header of the page. -->
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">Notifications</h1>
        <p class="lead">Checked the Notifications here.</p>
      </div>
    </div>

    {% if notifications %}
        <a href="{% url 'core:delete_all_read_notifications' %}" class="btn btn-secondary">Delete read notifications</a>
        <ul class="notifications">
          {% for notice in notifications %}
            {% include 'core/notice.html' %}
          {% endfor %}
        </ul>
    {% else %}
        <h1>
            You currently don't have any notifications!
        </h1>
    {% endif %}



{% endblock %}

fyp/templates/core/base.html
<!DOCTYPE html>

{% load staticfiles %}
{% load notification_tags %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator"
          content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'image/icon.png' %}">
    <title>
        My PhD - {% block title_block %}
            The default content for title block.
         {% endblock %}
    </title>

    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css"
          rel="stylesheet">
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css"
            rel="stylesheet">
</head>


<body>
 <header>
 <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
 {% if user.is_authenticated %}
      <a class="navbar-brand p-2" href="{% url 'core:dashboard' %}">My PhD</a>
 {% else %}
     <a class="navbar-brand p-2" href="{% url 'core:index' %}">My PhD</a>
 {% endif %}


 <button class="navbar-toggler" type="button" data-toggle="collapse"
         data-target="#navbarCollapse" aria-controls="navbarCollapse"
         aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
 </button>


 <div class="collapse navbar-collapse" id="navbarCollapse">
 <ul class="navbar-nav mr-auto">
 <li class="nav-item ">
 <a class="nav-link" href="{% url 'core:about' %}">About</a></li>
     {% if user.is_authenticated %}
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'core:logout' %}">Logout</a></li>
     {% else %}
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'core:register' %}">Register here</a></li>
     {% endif %}
 </ul>
 </div>
 </nav>
</header>

 <div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                {% block sidebar_block %}
                    {% if user.is_authenticated %}

         <ul class="nav flex-column">

          <li class="nav-item">
            <a class="nav-link {% block dashboard_tag %} {% endblock %}" href="{% url 'core:dashboard' %}">
              <span data-feather="home"></span>
              Dashboard <span class="sr-only">(current)</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link {% block connection_tag %} {% endblock %}" href="{% url 'core:connection' %}">
              <span data-feather="users"></span>
              Connection
            </a>
          </li>


          <li class="nav-item">
            <a class="nav-link {% block relationship_tag %} {% endblock %}" href="{% url 'core:add_new_relationship' %}">
              <span data-feather="users"></span>
              Relationship
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link {% block upload_tag %} {% endblock %}" href="{% url 'core:uploadfile' %}">
              <span data-feather="file-text"></span>
              Upload files
            </a>
          </li>

        </ul>

         <!--The secondary navigation bar.-->
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Messages</span>
          <a class="d-flex align-items-center text-muted" href="#">
            <span data-feather="message-square"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link {% block inbox_tag %} {% endblock %}" href="{% url 'core:show_message' %}">
              <span data-feather="mail"></span>
              Inbox
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link {% block outbox_tag %} {% endblock %}" href="{% url 'core:outbox' %}">
              <span data-feather="mail"></span>
              Outbox
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link {% block trash_tag %} {% endblock %}" href="{% url 'core:trash_box' %}">
              <span data-feather="trash-2"></span>
              Trash box
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link {% block send_message_tag %} {% endblock %}" href="{% url 'core:send_message' %}">
              <span data-feather="mail"></span>
              Send Message
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Notifications</span>
          <a class="d-flex align-items-center text-muted" href="#">
            <span data-feather="bell"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">

            <!--Add function: Mark all as read.-->
          <li class="nav-item">
            <a class="nav-link {% block Notification_tag %} {% endblock %}" href="{% url 'core:view_notifications' %}">
              <span data-feather="info"></span>
              Unread {% live_notify_badge badge_class="badge badge-secondary" %}
            </a>
          </li>

            <!--Add function: Delete all read message.-->
          <li class="nav-item">
            <a class="nav-link {% block Notification2_tag %} {% endblock %}" href="{% url 'core:all_notifications' %}">
              <span data-feather="info"></span>
              All notifications
            </a>
          </li>
        </ul>

                    {% endif %}
                {% endblock %}
            </div>
        </nav>

 <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
 {% block body_block %}


 {% endblock %}
         <footer>
         <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2019 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot;
        <a href="#">Terms</a></p>
        </footer>
        </main>
    </div>
 </div>





 <!-- Bootstrap core JavaScript -->
 <!-- Placed at the end of the document so the pages load faster -->
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
 <script>
 window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')
 </script>
 <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js">
 </script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js">
 </script>
 <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js">
 </script>
</body>
</html>

fyp/templates/core/candidate_registration.html
{% extends 'core/base.html' %}



{% load staticfiles %}

{% block title_block %}
    Candidate register
{% endblock %}


{% block body_block %}
    <h1>Register page for the candidate</h1>

	{% if registered %}
		<strong>Thank you for registering as a candidate!</strong>
        <strong>Later add a redirect link!</strong>
	{% else %}
		<strong>Register here!</strong>
		<form id="user_form" method="post" action="{% url 'core:canRegister' %}"
			enctype="multipart/form-data">

			{% csrf_token %}


			{{ user_form.as_p }}

			{{ profile_form.as_p }}

			<input type="submit" name="submit" value="Register" />

		</form>
	{% endif %}
{% endblock %}

fyp/templates/core/create_group.html
{% extends 'core/base.html' %}


{% block title_block %}
    Create group
{% endblock %}


{% block body_block %}
    <form method="post" action="{% url 'core:create_group'%}" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Back</button>
    </form>
{% endblock %}

fyp/templates/core/edit-file.html
{% extends 'core/base.html' %}


{% block title_block %}
    file
{% endblock %}



{% block body_block %}
    {% if file %}
        <strong>{{ file.name }}</strong>
    {% else %}
        <strong>The specified file does not exist!</strong>
    {% endif %}

    <form method="post" action="{% url 'core:edit_file'  file.id %}">

        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary">Save</button>
        <!-- Redirect to the same page and update the related information. -->


        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#shareModal">
            Share
        </button>

        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">Delete</button>
    </form>







    <!-- Pop up a form to let the user fill in the related information for sharing file. -->
    <!-- Modal -->
    <div class="modal fade" id="shareModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalCenterTitle">Share</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <!-- Later change this action so that it will redirect to the page which can handle this request. -->
            <form method="post" action="{% url 'core:send_message' file.id %}">
                {% csrf_token %}
                {{ share_form.as_p }}
              <div class="modal-footer">
                <!-- One way to do this is to use a redirect button like <a>-->
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Send</button>
              </div>
            </form>
          </div>

        </div>
      </div>
    </div>

    <!-- Should pop up a warning and let the user choose whether he wants to delete or not. -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalCenterTitle">Warning</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Are you sure to delete this file?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <a href="{% url 'core:delete_file' file.id %}" class="btn btn-danger">Delete</a>
          </div>
        </div>
      </div>
    </div>



{% endblock %}

fyp/templates/core/new_relationship.html
{% extends 'core/base.html' %}

{% load staticfiles %}

{% block title_block %}
    New relation
{% endblock %}

{% block body_block %}
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">Connections</h1>
        <p class="lead">Check here to see your connections with professors and groups!</p>
      </div>
    </div>

    {% if search %}
        {% if search_success %}
            {% include 'core/profile_card.html' %}
        {% else %}
            <p>The username you input cannot find a valid user!</p>
        {% endif %}
    {% endif %}

    <form>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" formmethod="get" class="btn btn-primary">Search</button>
        <button type="submit" formmethod="post" class="btn btn-primary">Request</button>
    </form>
{% endblock %}

fyp/templates/core/notification.html
{% extends 'core/base.html' %}


{% block title_block %}
    Notifications
{% endblock %}


{% block Notification_tag %}
    active
{% endblock %}

{% block body_block %}
        <!--A container for showing the header of the page. -->
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">Notifications</h1>
        <p class="lead">Checked the Notifications here.</p>
      </div>
    </div>

    <ul class="notifications">
      {% for notice in unread_notifications %}
        {% include 'core/notice.html' %}
      {% endfor %}
    </ul>


{% endblock %}

fyp/templates/core/profile.html
{% extends 'core/base.html' %}

{% load staticfiles %}


{% block title_block %}
    Profile for {{ selecteduser.username }}
{% endblock %}


{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">{{ selecteduser.username }}'s Profile</h1>
        </div>
    </div>


    <div class="container">
        <div class="row">
            <img src="{{ MEDIA_URL }}{{ userprofile.picture }}"
                width="300"
                height="300"
                alt="{{ selecteduser.username }}'s profile image" />
            <br />
            <div>
                {% if selecteduser == user %}
                    <!--The user can only update his own profile-->
                    <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Update" />
                    </form>
                {% else %}
                    <p>
                        <strong>You are not the user</strong>
                    </p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

fyp/templates/core/show_messages.html
{% extends 'core/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Messages
{% endblock %}

{% block inbox_tag %}
    active
{% endblock %}

{% block body_block %}

    <!--A container for showing the header of the page. -->
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">Messages</h1>
        <p class="lead">Checked the messages received here.</p>
      </div>
    </div>

    {% if messages %}
    <table class="table mb-0">
        <thead>
            <tr>
                <th>
                    Sender
                </th>

                <th>
                    Subject
                </th>

                <th>
                    Received
                </th>

                <th>
                    Action
                </th>
            </tr>
        </thead>

        <tbody>
            {% for message in messages %}
            <tr>
                <td>
                    {{ message.sender }}
                </td>
                <td>
                    {% if message.is_read %}
                        {{ message.subject }}
                    {% else %}
                        <strong>{{ message.subject }}</strong>
                    {% endif %}
                </td>

                <td>
                    {{ message.sent_at }}
                </td>

                <td>
                    <a href="{% url 'core:view_message' message.id %}" class="btn btn-primary btn-sm">Check</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>No messages.</p>
    {% endif %}

{% endblock %}

fyp/templates/core/unread_notification.html
{% extends 'core/base.html' %}


{% block title_block %}
    Notifications
{% endblock %}


{% block Notification_tag %}
    active
{% endblock %}

{% block body_block %}
        <!--A container for showing the header of the page. -->
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">Notifications</h1>
        <p class="lead">Checked the Notifications here.</p>
      </div>
    </div>

    {% if unread_notifications %}
        <a href="{% url 'core:mark_all_as_read' %}" class="btn btn-secondary">Mark all as read</a>

        <ul class="notifications">
          {% for notice in unread_notifications %}
            {% include 'core/notice.html' %}
          {% endfor %}
        </ul>
    {% else %}
        <h2> You don't have any unread notifications!</h2>
    {% endif %}



{% endblock %}

fyp/templates/core/upload_file.html
{% extends 'core/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}


{% block title_block %}
    Upload files
{% endblock %}

{% block upload_tag %}
    active
{% endblock %}

{% block body_block %}
    Upload files here.
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Upload file</button>
    </form>
{% endblock %}